package com.nhc.CareerNest.constant;

public enum JobTypeEnum {
    DEVELOPER,
    TESTER,
    DATA_ENGINEER,
    DATA_ANALYST,
    DATA_SCIENTIST,
    AI_ENGINEER,
    DEVOPS_ENGINEER,
    SYSTEM_ADMINISTRATOR,
    SECURITY_ENGINEER,
    NETWORK_ENGINEER,
    DATABASE_ADMINISTRATOR,
    EMBEDDED_ENGINEER,
    ERP_SPECIALIST,
    GAME_DEVELOPER,
    UI_UX_DESIGNER,
    PROJECT_MANAGER,
    BUSINESS_ANALYST,
    SCRUM_MASTER,
    BLOCKCHAIN_DEVELOPER,
    CLOUD_ENGINEER,
    IT_HELP_DESK
}
